title: Milestone Project
author: Jiwei Hu, Sanchit Singh, Khalid Abdilahi, Vera Cui

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: label

#repository:
  #url: https://github.com/suuuuperNOVA/index.html # Online location of your book
  #path_to_book: ""  # Optional path to your book, relative to the repository root
  #branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

#html:
  #use_issues_button: true
  #use_repository_button: true